name: bower
version: '1.8.0'
summary: A package manager for the web
description: |
  Web sites are made of lots of things — frameworks, libraries, assets, and utilities.
  Bower manages all these things for you.
grade: stable
confinement: strict

apps:
  bower:
    command: bower
  git:
    command: git
    environment:
      GIT_EXEC_PATH: $PATH:$SNAP/libexec/git-core
      GIT_TEMPLATE_DIR: $SNAP/share/git-core/templates
    plugs:
      - home
      - network

parts:
  bower:
    plugin: nodejs
    node-packages:
      - bower@1.8.0
    stage-packages:
      - gzip
      - git
      - curl
      - python
      - libssl-dev
      - pkg-config
      - build-essential
    after:
      - git
  git:
    source: https://github.com/git/git
    source-type: git
    source-depth: 1
    plugin: autotools
    configflags:
      - --with-curl
      - --with-expat
    build-packages:
      - gettext
      - libssl-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
    stage-packages:
      - libcurl3
